"use strict";
let pc = "Dell";
console.log("Is pc == 'Dell'?I predicted true");
console.log(pc == "Dell");
let country = "Pakistan";
console.log("Is country == 'Pakistan'?I predicted true");
console.log(country == "Pakistan");
let car = "BMW";
console.log("Is car == 'Honda Civic'?I predicted false");
console.log(car == "Honda Civic");
let city = "Newyork";
console.log("Is city == 'Pakistan'?I predicted false");
console.log(city == "Pakistan");
let program = "warr gaya";
console.log("Is program == 'warr gaya'?I predicted true");
console.log(program == "warr gaya");
let favouriteSports = "Cricket";
console.log("Is favouriteSports == 'Cricket'?I predicted true");
console.log(favouriteSports == "Cricket");
let Religion = "Islam";
console.log("Is Religion == 'Islam'?I predicted true");
console.log(Religion == "Islam");
let favouriteDish = "Biryani";
console.log("Is favouriteDish == 'handi'?I predicted false");
console.log(favouriteDish == "handi");
let password = "321";
console.log("Is password == '123'?I predicted false");
console.log(country == "123");
let weather = "cloudy";
console.log("Is weather == 'rainy'?I predicted false");
console.log(weather == "rainy");
